AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer + Target Group + Listener + Attachment

Parameters:
  VpcId:
    Type: String
  PublicSubnet1Id:
    Type: String
  PublicSubnet2Id:
    Type: String
  ALBSGId:
    Type: String
  TargetInstanceId:
    Type: String

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: webapp-alb
      Scheme: internet-facing
      SecurityGroups: [!Ref ALBSGId]
      Subnets:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id

  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  AttachInstance:
    Type: AWS::ElasticLoadBalancingV2::TargetGroupAttachment
    Properties:
      TargetGroupArn: !Ref TargetGroup
      TargetId: !Ref TargetInstanceId
      Port: 80

Outputs:
  ALBDNSName:
    Value: !GetAtt ALB.DNSName