AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with SSM role/profile and simple HTTP server

Parameters:
  VpcId:
    Type: String
  SubnetId:
    Type: String
  InstanceSGId:
    Type: String
  KeyName:
    Type: String
    Default: ''
    Description: Optional EC2 key pair name
  InstanceType:
    Type: String
    Default: t3.micro
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref InstanceRole]

  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          SubnetId: !Ref SubnetId
          GroupSet: [!Ref InstanceSGId]
      KeyName: !If [HasKey, !Ref KeyName, !Ref 'AWS::NoValue']
      UserData: !Base64 |
        #!/bin/bash
        set -eux
        dnf -y install httpd || yum -y install httpd
        echo "<h1>Hello from EC2 $(hostname)</h1>" > /var/www/html/index.html
        systemctl enable httpd
        systemctl start httpd

Conditions:
  HasKey: !Not [!Equals [!Ref KeyName, ""]]

Outputs:
  InstanceId:
    Value: !Ref WebInstance
  InstancePrivateIp:
    Value: !GetAtt WebInstance.PrivateIp


