version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo Starting rollback process...
      - echo Rolling back CloudFormation stack...
      - |
        # Get the last successful stack template
        aws cloudformation get-template \
          --stack-name web-infrastructure-$ENVIRONMENT \
          --template-stage Processed \
          --query 'TemplateBody' > previous-template.json
      - echo Initiating stack rollback...
      - |
        aws cloudformation cancel-update-stack \
          --stack-name web-infrastructure-$ENVIRONMENT || \
        aws cloudformation continue-update-rollback \
          --stack-name web-infrastructure-$ENVIRONMENT
      - echo Waiting for rollback to complete...
      - |
        aws cloudformation wait stack-update-complete \
          --stack-name web-infrastructure-$ENVIRONMENT
  post_build:
    commands:
      - echo Rollback completed
      - aws cloudformation describe-stacks --stack-name web-infrastructure-$ENVIRONMENT --query 'Stacks[0].StackStatus'