AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main template - 2-tier web infrastructure'

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prod]
    Description: Environment name (dev or prod)

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://web-templates-${Environment}-${AWS::AccountId}.s3.amazonaws.com/templates/network.yaml'
      Parameters:
        Environment: !Ref Environment

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://web-templates-${Environment}-${AWS::AccountId}.s3.amazonaws.com/templates/security.yaml'
      Parameters:
        Environment: !Ref Environment
        VPCId: !GetAtt NetworkStack.Outputs.VPCId

  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://web-templates-${Environment}-${AWS::AccountId}.s3.amazonaws.com/templates/alb.yaml'
      Parameters:
        Environment: !Ref Environment
        VPCId: !GetAtt NetworkStack.Outputs.VPCId
        PublicSubnetId: !GetAtt NetworkStack.Outputs.PublicSubnetId
        ALBSecurityGroupId: !GetAtt SecurityStack.Outputs.ALBSecurityGroupId

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://web-templates-${Environment}-${AWS::AccountId}.s3.amazonaws.com/templates/ec2.yaml'
      Parameters:
        Environment: !Ref Environment
        PrivateSubnetId: !GetAtt NetworkStack.Outputs.PrivateSubnetId
        EC2SecurityGroupId: !GetAtt SecurityStack.Outputs.EC2SecurityGroupId
        TargetGroupArn: !GetAtt ALBStack.Outputs.TargetGroupArn

Outputs:
  ALBDNSName:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt ALBStack.Outputs.ALBDNSName
    Export:
      Name: !Sub '${AWS::StackName}-ALB-DNSName'

  Environment:
    Description: Environment name
    Value: !Ref Environment
    Export:
      Name: !Sub '${AWS::StackName}-Environment'

  VPCId:
    Description: VPC ID
    Value: !GetAtt NetworkStack.Outputs.VPCId
    Export:
      Name: !Sub '${AWS::StackName}-VPC-ID'