AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Instance'

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prod]
  PrivateSubnetId:
    Type: String
  EC2SecurityGroupId:
    Type: String
  TargetGroupArn:
    Type: String

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}'
      InstanceType: t3.micro
      SubnetId: !Ref PrivateSubnetId
      SecurityGroupIds:
        - !Ref EC2SecurityGroupId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          ENVIRONMENT=${Environment}
          dnf update -y
          dnf install -y nginx
          systemctl enable nginx
          systemctl start nginx
          cat <<EOF > /usr/share/nginx/html/index.html
          <html>
          <head><title>${Environment} Server</title></head>
          <body>
          <h1>Hello from ${Environment} environment!</h1>
          <p>This page is served by Nginx on Amazon Linux 2023</p>
          </body>
          </html>
          EOF
      Tags:
        - Key: Name
          Value: !Sub 'web-ec2-${Environment}'

  TargetGroupAttachment:
    Type: AWS::ElasticLoadBalancingV2::TargetGroupAttachment
    Properties:
      TargetGroupArn: !Ref TargetGroupArn
      TargetId: !Ref EC2Instance
      Port: 80

Outputs:
  EC2InstanceId:
    Value: !Ref EC2Instance